version: "3.8"
services:
    nginx:
     # build:
     #  context: ./nginx
     #  dockerfile: Dockerfile
     image: nginx:1.21-alpine
     hostname: nginx
     container_name: layer-4-load-balancer
     networks:
        - lb-net
     ports:
        - 8080:9000
     volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
       - ./nginx/logs/:/var/log/nginx/
  
    
    app1:
     build:
      context: ./app
      dockerfile: Dockerfile
     hostname: app1
     container_name: app1
     networks:
        - lb-net
     environment:
        - PORT=3000
     ports:
        - 3000:3000
    
    app2:
     build:
      context: ./app
      dockerfile: Dockerfile
     hostname: app2
     container_name: app2
     networks:
        - lb-net
     environment:
        - PORT=9999
     ports:
        - 9999:9999

networks:
 lb-net:
   name: lb-net
   driver: bridge
